#!/bin/bash


tempdir=$(mktemp -d logfiles.XXX)
cd $tempdir

download(){
   n=0
   for file in {auth-fohls.log,auth-ilpro122.log,auth-ipc88.log,auth-ipo51.log}{,.{1,{2..4}.gz}}; do
      clear
      n=$(($n+1))
      echo Downloading file $n/20
	
      wget ilpro122.informatik.htw-dresden.de/logs/${file} 2> /dev/null
      if test $? -ne 0; then return 1; fi

      unzip=$(echo $file | grep ".gz" | wc -l)
      if test $unzip -eq 1; then
         echo Unzipping file
         gzip -d $file 2> /dev/null
         if test $? -ne 0; then return 1; fi
      fi 
   done
} 


rm *; cd .. ; rmdir $tempdir;

exit 0
